# Generated by Django 6.0.7 on 2026-07-14 10:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('demand', models.IntegerField(default=1)),
                ('time_window_open', models.CharField(default='08:00', max_length=10)),
                ('time_window_close', models.CharField(default='17:00', max_length=10)),
                ('service_time', models.IntegerField(default=5, help_text='Service time in minutes')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2)),
                ('road_status', models.BooleanField(default=True, help_text='True if road is accessible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['node_id'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(default='PSO', max_length=50)),
                ('n_nodes', models.IntegerField()),
                ('total_distance_km', models.FloatField()),
                ('computation_time_sec', models.FloatField()),
                ('time_window_violations', models.IntegerField(default=0)),
                ('route_feasibility_pct', models.FloatField()),
                ('parameters', models.JSONField(default=dict)),
                ('route_json', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pso_distance_km', models.FloatField()),
                ('baseline_distance_km', models.FloatField()),
                ('improvement_km', models.FloatField()),
                ('improvement_pct', models.FloatField()),
                ('pso_better', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('optimization_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='routing.optimizationrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
