# Generated by Django 6.0.7 on 2026-07-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisonresult',
            old_name='pso_better',
            new_name='aco_better',
        ),
        migrations.RenameField(
            model_name='comparisonresult',
            old_name='pso_distance_km',
            new_name='aco_distance_km',
        ),
        migrations.AlterField(
            model_name='optimizationrun',
            name='algorithm',
            field=models.CharField(default='ACO', max_length=50),
        ),
    ]
