# Generated by Django 6.0.7 on 2026-07-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_rename_pso_better_comparisonresult_aco_better_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypoint',
            name='address',
            field=models.CharField(blank=True, help_text='Alamat lengkap', max_length=255, null=True),
        ),
    ]
