# Generated by Django 6.0.7 on 2026-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_deliverypoint_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypoint',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Utama'), (2, 'Biasa')], default=2),
        ),
    ]
